EvergenEnergy/remote-commands-handler

app/configuration.py
app/mqtt_client.py
config/configuration.yml
dockerfile
main.py
run.sh
tests/config/configuration_test.py

Use of a bash script allows us to use env variables in the docker and docker-compose to more easily set the configuration path variable.

use run.sh to set configuration path

---

.github/workflows/docker-publish.yaml
app/modbus_client.py
config/configuration.yml

* Use semver when we publish new tags
* Use branch name when we publish to main
* Update default ports using sensible values
* Flag the ModbusClient private

Ensure we use semver when we publish new tags

---

.github/workflows/ci.yaml
app/configuration.py
app/modbus_client.py
app/mqtt_client.py
main.py
poetry.lock
pyproject.toml
tests/app/test_modbus_client.py
tests/app/test_mqtt_client.py
tests/config/configuration_test.py

* Adding black as linter
* Update files accordingly
* 
Black is a good tool to respect PEP 8, including enforcement of empty new lines on python file
If I now have this:
```
diff --git a/app/mqtt_client.py b/app/mqtt_client.py
index 54bab8b..87a677e 100644
--- a/app/mqtt_client.py
+++ b/app/mqtt_client.py
@@ -55,4 +55,4 @@ class MqttClient:
for callback in self.on_message_callbacks:
callback(msg)
-        return inner
+        return inner
\ No newline at end of file
```
When I run `poetry run black --check .` I get:
```
(remote-comands-handler-py3.11) ➜  remote-commands-handler git:(linting-black) ✗ poetry run black --check .
would reformat /Users/sebastianmachuca/projects/remote-commands-handler/app/mqtt_client.py
Oh no! 💥 💔 💥
1 file would be reformatted, 7 files would be left …
```

Adding black as a (auto)linter for some things that pylint doesn't cover

---

app/mqtt_client.py
main.py
tests/app/test_modbus_client.py

Enable logging
We shouldn't be using `print`. Logging allow us to differentiate levels

Enable logging rather than print

---

README.md
app/configuration.py
app/exceptions.py
main.py
tests/config/configuration_test.py
tests/config/invalid_syntax_configuration.yaml

- perform some validation on the specified configuration file to ensure all required attributes are present
- add some tests
- add some details to the README on how to modify config (not 100% across the terminology yet so please make suggestions if anything doesn't sound right)
Strict checking of configuration on startup means we need less runtime error handling
I tested each aspect of the validation code manually and have added unit tests to cover most aspects.

UTIL-564: validate config on startup

---

.github/workflows/docker-validator.yaml
Dockerfile
docker-compose.yaml

Use a docker image as github action to run docker validation
The current process isn't working very well. After I kicked a new tag, I got the [following error](https://github.com/EvergenEnergy/remote-commands-handler/actions/runs/5195451247/jobs/9368184115):
```
Run hadolint --ignore DL3008 **/Dockerfile
hadolint: **/Dockerfile: withBinaryFile: does not exist (No such file or directory)
Error: Process completed with exit code 1.
```
I run the equivalent action locally: 
```
remote-commands-handler git:(add-inital-integration-tests) ✗ docker run --rm -i hadolint/hadolint < Dockerfile
-:11 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your …
```

Use GitHub Action to perform Dockerfile validation

---

app/exceptions.py
app/memory_order.py
tests/app/test_modbus_client.py
tests/app/test_mqtt_client.py
tests/config/test_configuration.py
tests/config/test_memory_order.py

* switch from unittest to pytest style in a couple of tests (we still reference the mock lib as unittest.mock)
* some small changes to increase coverage in configuration.py and memory_order.py
Consistency and better coverage. The tests for modbus_client and mqtt_client are still WIP
CI is happy so far

UTIL-559: improve coverage

---

tests/app/test_modbus_client.py

Simplify the modbus client test to use a mock for the internal Modbus client
Faster and less flaky. There is less need for TCP testing in unit tests now that we have an E2E test
CI

UTIL-559: use simpler mock for testing modbus

---

tests/app/test_mqtt_client.py

Explicitly call callbacks to get 100% coverage of `mqtt_client.py`.
In a couple of places this is just checking log messages for errors - this will hopefully improve with more error handling
More coverage = better
CI

Increase coverage on MQTT test

---

.dockerignore
Makefile
app/configuration.py
tests/config/test_configuration.py

* validate the keys within config sections as well as the sections themselves
* added a handy Makefile I've been using, just has some shortcuts for local development - happy to remove if not appropriate to commit
The code expects these config values to be provided 
Existing tests was extended to check for the 'host' key

More config validation

---

app/configuration.py
tests/config/test_configuration.py

Additional config validation checks:
- when a section is present but not the expected data type
- any TypeErrors during validation for unanticipated config file weirdness
Also catch TypeError and KeyError when constructing the Configuration object itself - this will catch developer errors where a key is assumed to exist but not checked for in validation.
We can't anticipate in advance everything that might be wrong with a config file, so this aims to catch errors more generally. 
We're assuming that when a developer adds a new key to the config file, they must also add a check for it to the validation function. If they don't, the process will fail to start, but it will hopefully fail with a somewhat readable error.
CI but also by manually changing keys within configuration.py after …

Catch type errors in config validation

---

app/configuration.py
app/exceptions.py
app/message.py
app/modbus_client.py
app/mqtt_client.py
main.py
tests/app/test_message.py
tests/app/test_modbus_client.py
tests/app/test_mqtt_client.py

Add custom exceptions and logging for error scenarios including:
- incoming message with malformed JSON or missing object keys
- incoming message with an action that doesn't match any known config
- failure to send to to Modbus
- badly formed `command_topic` in config
There is also a change to the callback functions used when messages are received:
- the main process now calls a single callback which looks for matching coils and registers, so that we can raise an error if neither are matched
- parsing and validation of the MQTT message happens in a new module rather than within main.py, and is performed within the MQTT `_on_message` callback
We want to catch all possible runtime errors to ensure that they don't kill the main process. An error reporting mechanism is still to be added, but …

Add handling for more error scenarios

---

app/configuration.py
config/configuration.yaml
tests/config/example_configuration.yaml
tests/config/test_configuration.py

* Accept an optional config setting specifying an MQTT topic to publish errors to
* Set a bool value to true if topic is supplied and of non-zero length
* Check that it's a valid topic names and doesn't contain wildcard chars (because it's for publishing not subscribing)
This will enable the service to send error messages when the topic is configured
Automated tests check that config file validation is successful with or without the error_topic

Configure optional error topic

---

README.md
app/configuration.py
app/error_handler.py
app/mqtt_reader.py
config/configuration.yaml
main.py
tests/app/test_error_handler.py
tests/app/test_modbus_client.py
tests/app/test_mqtt_reader.py
tests/config/bad_env_var_configuration.yaml
tests/config/example_configuration.yaml
tests/config/good_env_var_configuration.yaml
tests/config/test_configuration.py
tests/end-to-end/configuration.yaml
tests/end-to-end/test_able_to_sent_to_commands.py

- Add a `site_settings` section to config containing `site_name` and `serial_number`
- These values can be defined in the file or will be read from the environment if the values are `$SITE_NAME`/`$SERIAL_NUMBER`
- Fail the config read if the site setting values look like env vars but don't match those names, or if the specified env vars are empty
- Log the values on startup and use them in the MQTT topic when publishing error messages
- Simplify ErrorHandler construction and set those values as attributes
- Add a callback for disconnection from the MQTT broker so we log an error if we unexpectedly lose contact
- Add an E2E tests which verifies that error messages are sent, and that commands will still be received afterwards
We will need site/serial to distinguish error messages from …

Use environment variables in config settings

---

app/error_handler.py
app/message.py
app/modbus_client.py
app/mqtt_reader.py
app/payload_builder.py
main.py
tests/app/test_message.py
tests/app/test_modbus_client.py
tests/app/test_mqtt_reader.py
tests/app/test_mqtt_writer.py

- Only catch the base `Exception` class in one spot, at top-most level
- Don't use `assert` in runtime code (http://www.aleax.it/pycon16.pdf)
- Make ModbusClient write methods private so everything has to go through `write_command`
- Change tests to use `setup_method` instead of `setup_class` so all mocks are created fresh for each test
It's not considered good practice to catch the `Exception` class, but we do want to ensure that nothing that happens during message processing can rise up and kill the main process. So I've adjusted things so that each module handles the exceptions that we can predict, and then anything else will be caught at the top-most level, inside the `_on_message` callback (which encompasses all processing from reading the incoming message, to invoking other …

Improve error handling to use best practice

---

README.md

Update the README to include current information on using env vars in config file.
Info in README was out of date.
No testing needed
Please remember that this repository is open source. Be careful to avoid including any sensitive information in your changes or your comments. If you need to discuss something sensitive, please do so through a private channel.

UTIL-617: update README

---

.github/workflows/ci.yaml

Add GH token to the coverall step
Dependabot is currently failing:
https://github.com/EvergenEnergy/remote-commands-handler/pull/46
```
Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.
Traceback (most recent call last):
File "/home/runner/.cache/pypoetry/virtualenvs/remote-comands-handler-NkRyAW_2-py3.11/lib/python3.11/site-packages/coveralls/cli.py", line 64, in main
coverallz = Coveralls(token_required,
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/.cache/pypoetry/virtualenvs/remote-comands-handler-NkRyAW_2-py3.11/lib/python3.11/site-packages/coveralls/api.py", line 49, in __init__
self.ensure_token()
File "/home/runner/.cache/pypoetry/virtualenvs/remote-comands-handler-NkRyAW_2-py3.11/lib/python3.11/site-pack …
```

Add GH token to the coveralls step

---

tests/end-to-end/configuration.yaml
tests/end-to-end/test_able_to_sent_to_commands.py

* Correct the number of registers to read for each data type, we were specifying twice as many as needed
* Increase the magnitude of random values used in testing, as higher values seem to involve greater loss of precision
* Use approx rather than round to handle slight loss of precision in 32-bit floats
* Rename first test register for clarity
Mainly to be more explicit about what tests are doing, and increase robustness
Tests seem to pass consistently. When testing locally I noticed frequent failures using higher values for 32-bit floats when comparing with round, but switching to approx resolved this.
Please remember that this repository is open source. Be careful to avoid including any sensitive information in your changes or your comments. If you need to discuss something sensitive, …

Adjustments to E2E tests

---

app/configuration.py
app/message.py
app/modbus_client.py
tests/app/test_message.py
tests/config/example_configuration.yaml
tests/config/test_configuration.py
tests/end-to-end/configuration.yaml
tests/end-to-end/test_send_and_read_back_command_values.py

* Add a config setting which inverts the sign of values before writing to modbus
* Add config validation so you can't do this on an unsigned integer field
* Catch struct.error exceptions which happen if you try to do this anyway
* Add unit tests
* Add e2e tests
Needed so that values can be inverted when passing between systems which represent import/export values with opposite signs
Automated tests
Please remember that this repository is open source. Be careful to avoid including any sensitive information in your changes or your comments. If you need to discuss something sensitive, please do so through a private channel.

Add sign inversion

---

docker-compose.yaml

Use the pymodbus image generated in https://github.com/EvergenEnergy/pymodbus-image/
The pymodbus project are no longer produced a docker image.
E2E tests pass when running this image in docker-compose

Use evergen docker image for pymodbus

---

app/memory_order.py
app/mqtt_reader.py
main.py
poetry.lock
pyproject.toml
tests/app/test_mqtt_reader.py
tests/config/test_configuration.py
tests/config/test_memory_order.py
tests/end-to-end/test_send_and_read_back_command_values.py

* Upgrade pymodbus from 3.2.2 to 3.6.8 with [breaking API changes](https://pymodbus.readthedocs.io/en/latest/source/api_changes.html)
* Upgrade paho-mqtt from 1.6.1 to 2.0.0 with [breaking API changes](https://eclipse.dev/paho/files/paho.mqtt.python/html/migrations.html) 
To ensure stability with latest functionality
Test suite passes

Upgrade deps

---

app/message.py
app/mqtt_reader.py
tests/app/test_message.py
tests/app/test_mqtt_reader.py
tests/end-to-end/test_send_and_read_back_command_values.py

* add a `CommandMessageList` class and move the `read` method there
* update all tests to send a list of commands as JSON payload
* add some tests with multiple commands
Being able to send multiple commands in a single message increases efficiency and allows for values of different registers to be tightly linked together.
Tested in a local deployment with list-format messages being sent from the cloud and standby service.

Expect a list of commands as MQTT message payload
